import React, { Component } from 'react';
import "./../Css/main.css"

class Strategies extends Component {
    render() {
        return <div className="componenet_bg">
            <div
                id='Strategies'
                className="row"
                style={{ margin: "5em" }}
            >
                <div className='col-1 col-sm-none'>
                </div>
                <div className="col-md-11 col-sm-11 p-5">
                    <span className="heading1">Strategies we will invest in</span>
                    <p
                        className="p_text"
                    >
                        dFuse, through its vaults, aims to maximise the return generated on the vault’s base asset.
                        For eg the dFuse’s ATOM vault aims to maximise the ATOM rewards generated by intelligently
                        allocating ATOM to a variety of options available such as Staking, Liquid Staking, Lending and
                        becoming LP of an ATOM AMM pool such as ATOM/OSMO and ATOM/JUNO.
                        <br />
                        <br />
                        The aim is to maximise return while keeping the risk below a certain threshold. While the APR of
                        LP pools are high(mostly) in comparison to staking/lending APR, the risks associated with allocating
                        to LP pools are also higher. The major risk is getting an unwanted exposure to coins other than the
                        base vault coin. For example, in order to contribute ATOM to ATOM/OSMO pool, the user has to first sell
                        half of their ATOM for OSMO and contribute to the pool. If OSMO underperforms ATOM, the pool will end up
                        with less ATOM and more OSMO. The user is also exposed to impermanence loss associated with the LP pool.
                        If the LP pool APR is not able to offset the risks associated with putting the base vault asset into the
                        LP pool, it will be wise to not allocate capital to the pool. Typically, staking/lending have low APR and
                        low risk whereas LP pools have high APR and higher risk. Deciding on the optimal mix is a rather tough
                        problem. A simple rule based approach for eg: allocating equal capital i.e. 50% to staking/lending and
                        50% to LP pool has a much higher risk contribution({'>90%'}) concentrated to the LP pool.
                        <br />
                        <br />
                        In order to solve this, dFuse aims to use the ‘Risk Parity’ Approach to come up with an optimal
                        allocation for each of the options.

                    </p>
                </div>
            </div>
        </div>
    }
}

export default Strategies;